### ISSUE TITLE
Feature Request: Change "Untag when Targeted" to a Toggle/Checkbox

### ISSUE THREAD

**Issue by Marstead** [DrJam/recently-killed-highlight#2]
Hello! I found your plugin recently and it has been amazing for my use case. I have a restricted iron account that is only allowed to interact with skilling nodes and monsters once in my unlocked regions, exhausting them. I then "reset" these exhausted enemies and nodes once I finish exhausting everything available to me. Since this plugin automatically tags NPCs that have recently died it saves me the trouble of having to manually tag every NPC I target in the NPC Indicators plugin.

I understand my use case is very different from the intended use case (barraging enemies) and is also supporting a pretty narrow game mode that, at the moment, is only played by me. But I have a handful of feature suggestions that would make this plugin invaluable for my restrictions and the restrictions of any future Iron accounts trying something similar. It might also have some unexpected general utility for regular players beyond the intent of your plugin. If this is expanding the scope of your plugin concept too much, feel free to reject these requests, but I think any features added can be made optional so that the default functionality (helping with barraging) remains the same.

*****

**FEATURE REQUEST:** Right now, the plugin automatically untags killed NPCs when they target you. It would be very nice if this could be changed to a toggle checkbox that defaults to ON. If unchecked, NPCs will remain tagged even after they target you.

**Comment by DrJam** [comment]
👍 [done](https://github.com/DrJam/recently-killed-highlight/commit/34020eb9b0031e6cf42b32b013d3727f5d0fb3cd), coming when update approved

**Comment by Marstead** [comment]
> 👍 [done](https://github.com/DrJam/recently-killed-highlight/commit/34020eb9b0031e6cf42b32b013d3727f5d0fb3cd), coming when update approved

You rule, thank you so much! I have a couple more that might be a bit more complicated or out of scope so feel free to delay or reject as needed once I open them.

**Comment by Marstead** [comment]
Hey hey, I tested these features with the Runelite update this morning and they're exactly what I needed for my series. Thank you so much for pushing them out so fast!

So the other features I mentioned don't really fit in this plugin's scope and I imagine might require some significant effort, probably requiring a separate, new RuneLite plugin. I also expect they might have a much narrower use case (not terribly useful except for folks attempting my specific game mode/restrictions). Would you be interested in maybe doing a paid commission to develop a second RL plugin? It's likely I'd be be one of the only ones using the plugin I'd want to make sure I pay you for your time. If you're interested in taking a look, shoot me a Discord DM: **Marstead#0001**; here's a Requirements Document for it: https://docs.google.com/document/d/1dLbg50JVWo5GZYSAedMokDLALfNPUVz6SKNhM6P0WIE

 Either way, thank you again for this update!
