### ISSUE TITLE
Feature Request: "Limit Remembered NPCs" Toggle/Checkbox

### ISSUE THREAD

**Issue by Marstead** [DrJam/recently-killed-highlight#3]
By default, the plugin has an option to increase or decrease the number of remembered NPCs, up to a maximum of 25. It would be nice to have a checkbox called "Limit Remembered NPCs" that defaults to ON. If unchecked, the plugin will remember/tag an unlimited number of killed NPCs. (NPC Indicators, which already supports this functionality, can remember hundreds or thousands of NPC IDs in the same session).

**Comment by DrJam** [comment]
👍 [done](https://github.com/DrJam/recently-killed-highlight/commit/c819363cfede0b7bbb28a441ba9d49d35fd189d9), coming when update approved
